//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _006_ConsomeWCFAssincrono.ProxyContact {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/_004_WCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Contact : _006_ConsomeWCFAssincrono.ProxyContact.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalContactInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailPromotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NameStyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalContactInfo {
            get {
                return this.AdditionalContactInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalContactInfoField, value) != true)) {
                    this.AdditionalContactInfoField = value;
                    this.RaisePropertyChanged("AdditionalContactInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailPromotion {
            get {
                return this.EmailPromotionField;
            }
            set {
                if ((this.EmailPromotionField.Equals(value) != true)) {
                    this.EmailPromotionField = value;
                    this.RaisePropertyChanged("EmailPromotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NameStyle {
            get {
                return this.NameStyleField;
            }
            set {
                if ((this.NameStyleField.Equals(value) != true)) {
                    this.NameStyleField = value;
                    this.RaisePropertyChanged("NameStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.Contact))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.Contact))]
    public partial class EntityObject : _006_ConsomeWCFAssincrono.ProxyContact.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _006_ConsomeWCFAssincrono.ProxyContact.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _006_ConsomeWCFAssincrono.ProxyContact.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _006_ConsomeWCFAssincrono.ProxyContact.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _006_ConsomeWCFAssincrono.ProxyContact.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.Contact[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.Contact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_006_ConsomeWCFAssincrono.ProxyContact.StructuralObject))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyContact.IContact")]
    public interface IContact {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContact/GetFirst10", ReplyAction="http://tempuri.org/IContact/GetFirst10Response")]
        _006_ConsomeWCFAssincrono.ProxyContact.Contact[] GetFirst10();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IContact/GetFirst10", ReplyAction="http://tempuri.org/IContact/GetFirst10Response")]
        System.IAsyncResult BeginGetFirst10(System.AsyncCallback callback, object asyncState);
        
        _006_ConsomeWCFAssincrono.ProxyContact.Contact[] EndGetFirst10(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContact/GetByContactId", ReplyAction="http://tempuri.org/IContact/GetByContactIdResponse")]
        _006_ConsomeWCFAssincrono.ProxyContact.Contact GetByContactId(int contactID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IContact/GetByContactId", ReplyAction="http://tempuri.org/IContact/GetByContactIdResponse")]
        System.IAsyncResult BeginGetByContactId(int contactID, System.AsyncCallback callback, object asyncState);
        
        _006_ConsomeWCFAssincrono.ProxyContact.Contact EndGetByContactId(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactChannel : _006_ConsomeWCFAssincrono.ProxyContact.IContact, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFirst10CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFirst10CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _006_ConsomeWCFAssincrono.ProxyContact.Contact[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_006_ConsomeWCFAssincrono.ProxyContact.Contact[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByContactIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByContactIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _006_ConsomeWCFAssincrono.ProxyContact.Contact Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_006_ConsomeWCFAssincrono.ProxyContact.Contact)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactClient : System.ServiceModel.ClientBase<_006_ConsomeWCFAssincrono.ProxyContact.IContact>, _006_ConsomeWCFAssincrono.ProxyContact.IContact {
        
        private BeginOperationDelegate onBeginGetFirst10Delegate;
        
        private EndOperationDelegate onEndGetFirst10Delegate;
        
        private System.Threading.SendOrPostCallback onGetFirst10CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByContactIdDelegate;
        
        private EndOperationDelegate onEndGetByContactIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetByContactIdCompletedDelegate;
        
        public ContactClient() {
        }
        
        public ContactClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetFirst10CompletedEventArgs> GetFirst10Completed;
        
        public event System.EventHandler<GetByContactIdCompletedEventArgs> GetByContactIdCompleted;
        
        public _006_ConsomeWCFAssincrono.ProxyContact.Contact[] GetFirst10() {
            return base.Channel.GetFirst10();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFirst10(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFirst10(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _006_ConsomeWCFAssincrono.ProxyContact.Contact[] EndGetFirst10(System.IAsyncResult result) {
            return base.Channel.EndGetFirst10(result);
        }
        
        private System.IAsyncResult OnBeginGetFirst10(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetFirst10(callback, asyncState);
        }
        
        private object[] OnEndGetFirst10(System.IAsyncResult result) {
            _006_ConsomeWCFAssincrono.ProxyContact.Contact[] retVal = this.EndGetFirst10(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFirst10Completed(object state) {
            if ((this.GetFirst10Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFirst10Completed(this, new GetFirst10CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFirst10Async() {
            this.GetFirst10Async(null);
        }
        
        public void GetFirst10Async(object userState) {
            if ((this.onBeginGetFirst10Delegate == null)) {
                this.onBeginGetFirst10Delegate = new BeginOperationDelegate(this.OnBeginGetFirst10);
            }
            if ((this.onEndGetFirst10Delegate == null)) {
                this.onEndGetFirst10Delegate = new EndOperationDelegate(this.OnEndGetFirst10);
            }
            if ((this.onGetFirst10CompletedDelegate == null)) {
                this.onGetFirst10CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFirst10Completed);
            }
            base.InvokeAsync(this.onBeginGetFirst10Delegate, null, this.onEndGetFirst10Delegate, this.onGetFirst10CompletedDelegate, userState);
        }
        
        public _006_ConsomeWCFAssincrono.ProxyContact.Contact GetByContactId(int contactID) {
            return base.Channel.GetByContactId(contactID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetByContactId(int contactID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByContactId(contactID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _006_ConsomeWCFAssincrono.ProxyContact.Contact EndGetByContactId(System.IAsyncResult result) {
            return base.Channel.EndGetByContactId(result);
        }
        
        private System.IAsyncResult OnBeginGetByContactId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int contactID = ((int)(inValues[0]));
            return this.BeginGetByContactId(contactID, callback, asyncState);
        }
        
        private object[] OnEndGetByContactId(System.IAsyncResult result) {
            _006_ConsomeWCFAssincrono.ProxyContact.Contact retVal = this.EndGetByContactId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByContactIdCompleted(object state) {
            if ((this.GetByContactIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByContactIdCompleted(this, new GetByContactIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByContactIdAsync(int contactID) {
            this.GetByContactIdAsync(contactID, null);
        }
        
        public void GetByContactIdAsync(int contactID, object userState) {
            if ((this.onBeginGetByContactIdDelegate == null)) {
                this.onBeginGetByContactIdDelegate = new BeginOperationDelegate(this.OnBeginGetByContactId);
            }
            if ((this.onEndGetByContactIdDelegate == null)) {
                this.onEndGetByContactIdDelegate = new EndOperationDelegate(this.OnEndGetByContactId);
            }
            if ((this.onGetByContactIdCompletedDelegate == null)) {
                this.onGetByContactIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByContactIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetByContactIdDelegate, new object[] {
                        contactID}, this.onEndGetByContactIdDelegate, this.onGetByContactIdCompletedDelegate, userState);
        }
    }
}
