//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace _005_CustomizarEdmx
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pessoa> Pessoas
        {
            get
            {
                if ((_Pessoas == null))
                {
                    _Pessoas = base.CreateObjectSet<Pessoa>("Pessoas");
                }
                return _Pessoas;
            }
        }
        private ObjectSet<Pessoa> _Pessoas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produtos
        {
            get
            {
                if ((_Produtos == null))
                {
                    _Produtos = base.CreateObjectSet<Produto>("Produtos");
                }
                return _Produtos;
            }
        }
        private ObjectSet<Produto> _Produtos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pessoas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPessoas(Pessoa pessoa)
        {
            base.AddObject("Pessoas", pessoa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produtos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProdutos(Produto produto)
        {
            base.AddObject("Produtos", produto);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Pessoa> GetPessoas()
        {
            return base.ExecuteFunction<Pessoa>("GetPessoas");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<Pessoa> GetPessoas(MergeOption mergeOption)
        {
            return base.ExecuteFunction<Pessoa>("GetPessoas", mergeOption);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Perecivel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Perecivel : Produto
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Perecivel object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="property">Initial value of the Property property.</param>
        /// <param name="vencimento">Initial value of the Vencimento property.</param>
        public static Perecivel CreatePerecivel(global::System.Int32 id, global::System.String nome, global::System.Decimal property, global::System.DateTime vencimento)
        {
            Perecivel perecivel = new Perecivel();
            perecivel.Id = id;
            perecivel.Nome = nome;
            perecivel.Property = property;
            perecivel.Vencimento = vencimento;
            return perecivel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Vencimento
        {
            get
            {
                return _Vencimento;
            }
            set
            {
                OnVencimentoChanging(value);
                ReportPropertyChanging("Vencimento");
                _Vencimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vencimento");
                OnVencimentoChanged();
            }
        }
        private global::System.DateTime _Vencimento;
        partial void OnVencimentoChanging(global::System.DateTime value);
        partial void OnVencimentoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Pessoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pessoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pessoa object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        public static Pessoa CreatePessoa(global::System.Int32 id, global::System.String nome, Endereco endereco)
        {
            Pessoa pessoa = new Pessoa();
            pessoa.Id = id;
            pessoa.Nome = nome;
            pessoa.Endereco = StructuralObject.VerifyComplexObjectIsNotNull(endereco, "Endereco");
            return pessoa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeConjuge
        {
            get
            {
                return _NomeConjuge;
            }
            set
            {
                OnNomeConjugeChanging(value);
                ReportPropertyChanging("NomeConjuge");
                _NomeConjuge = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeConjuge");
                OnNomeConjugeChanged();
            }
        }
        private global::System.String _NomeConjuge;
        partial void OnNomeConjugeChanging(global::System.String value);
        partial void OnNomeConjugeChanged();

        #endregion
        #region Complex Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmComplexPropertyAttribute()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [XmlElement(IsNullable=true)]
        [SoapElement(IsNullable=true)]
        [DataMemberAttribute()]
        public Endereco Endereco
        {
            get
            {
                _Endereco = GetValidValue(_Endereco, "Endereco", false, _EnderecoInitialized);
                _EnderecoInitialized = true;
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = SetValidValue(_Endereco, value, "Endereco");
                _EnderecoInitialized = true;
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private Endereco _Endereco;
        private bool _EnderecoInitialized;
        partial void OnEnderecoChanging(Endereco value);
        partial void OnEnderecoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Perecivel))]
    public abstract partial class Produto : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Property
        {
            get
            {
                return _Property;
            }
            set
            {
                OnPropertyChanging(value);
                ReportPropertyChanging("Property");
                _Property = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property");
                OnPropertyChanged();
            }
        }
        private global::System.Decimal _Property;
        partial void OnPropertyChanging(global::System.Decimal value);
        partial void OnPropertyChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Model", Name="Endereco")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Endereco : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endereco object.
        /// </summary>
        /// <param name="rua">Initial value of the Rua property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="cEP">Initial value of the CEP property.</param>
        /// <param name="complemento">Initial value of the Complemento property.</param>
        public static Endereco CreateEndereco(global::System.String rua, global::System.Int32 numero, global::System.String cEP, global::System.String complemento)
        {
            Endereco endereco = new Endereco();
            endereco.Rua = rua;
            endereco.Numero = numero;
            endereco.CEP = cEP;
            endereco.Complemento = complemento;
            return endereco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rua
        {
            get
            {
                return _Rua;
            }
            set
            {
                OnRuaChanging(value);
                ReportPropertyChanging("Rua");
                _Rua = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rua");
                OnRuaChanged();
            }
        }
        private global::System.String _Rua;
        partial void OnRuaChanging(global::System.String value);
        partial void OnRuaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.Int32 _Numero;
        partial void OnNumeroChanging(global::System.Int32 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Complemento
        {
            get
            {
                return _Complemento;
            }
            set
            {
                OnComplementoChanging(value);
                ReportPropertyChanging("Complemento");
                _Complemento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Complemento");
                OnComplementoChanged();
            }
        }
        private global::System.String _Complemento;
        partial void OnComplementoChanging(global::System.String value);
        partial void OnComplementoChanged();

        #endregion
    }

    #endregion
    
}
